- .backlog/tasks/task-68 - verify-windows-binary-uses-.exe.md
- scripts/cli-download.cjs
- scripts/cli.cjs
- scripts/getBinaryName.cjs
- src/test/getBinaryName.test.ts
The Windows .exe extension handling has been fully implemented:
1. **getBinaryName.cjs** (shared utility):
- Correctly detects Windows platform using `process.platform === "win32"`
- Appends `.exe` extension to binary names on Windows
- Maps Node.js platform names to Bun target names appropriately
2. **cli.cjs** (wrapper script):
- Uses `getBinaryName()` to resolve the correct binary name including `.exe` on Windows
- Spawns the binary with `windowsHide: true` option for better Windows compatibility
3. **cli-download.cjs** (download script):
- Uses `getBinaryName()` to download the correct binary with `.exe` extension on Windows
- Skips chmod operation on Windows (only sets executable permissions on Unix)
- Also uses `windowsHide: true` when spawning the downloaded binary
4. **Test …
> TASK-68 - Verify Windows binary uses .exe

- .backlog/tasks/task-73 - fix-cli-windows-package-name.md
- .backlog/tasks/task-73 - fix-windows-binary-package-name-resolution.md
- .github/workflows/release.yml
- bun.lock
- scripts/cli.cjs
- scripts/resolveBinary.cjs
- src/test/resolveBinary.test.ts
- Added resolveBinary.cjs to map win32 to windows and exported helpers
- Updated cli.cjs to use resolveBinaryPath for selecting binary
- Modified release workflow to package resolveBinary.cjs
- Created unit tests for getPackageName mapping
> TASK-73 - Fix Windows binary package name

- .backlog/tasks/task-79 - fix-task-list-ordering-sort-by-decimal-id-not-string.md
- src/board.ts
- src/file-system/operations.ts
- src/test/board-ui-selection.test.ts
- src/test/filesystem.test.ts
- src/test/task-sorting.test.ts
- src/ui/board.ts
- src/utils/task-sorting.ts
The task list ordering issue was caused by using string comparison (`localeCompare`) for task IDs in the `FileSystem.listTasks()` method. This resulted in incorrect ordering where task-10 appeared before task-2.
- Created a new utility module `src/utils/task-sorting.ts` with functions for numeric task ID comparison
- `parseTaskId()` - Extracts numeric components from task IDs (handles both simple and decimal IDs)
- `compareTaskIds()` - Compares two task IDs numerically
- `sortByTaskId()` - Sorts an array of tasks by ID without mutating the original array
1. Updated `src/file-system/operations.ts` to use `sortByTaskId()` instead of `localeCompare`
2. Applied the fix to both `listTasks()` and `listDecisionLogs()` for consistency
3. The board view already had proper numeric sorting via the …
> TASK-79 - Fix task list ordering - sort by decimal ID not string

- .backlog/archive/tasks/task-81 - test-mixed-case-filename.md
- .backlog/archive/tasks/task-82 - UPDATED-Title-With-CAPS.md
- .backlog/tasks/task-80 - preserve-case-in-task-filenames-for-better-agent-discoverability.md
- src/file-system/operations.ts
- src/test/filesystem.test.ts
1. Removed `.toLowerCase()` from the `sanitizeFilename` method in `src/file-system/operations.ts`
2. Added test case "should preserve case in filenames" to verify mixed-case preservation
3. Updated document test expectations to match preserved case ("API-Guide" instead of "api-guide")
> Preserve case in task filenames for better agent discoverability

- .backlog/tasks/task-81 - fix-task-list-navigation-skipping-issue.md
- src/ui/components/generic-list.ts
The issue was in `/src/ui/components/generic-list.ts` - there were conflicting navigation systems causing race conditions.
**Root Cause:** 
- Task list view uses `GenericList` component with `keys: true` (blessed's built-in navigation)
- Custom key handlers were also defined, creating conflicts
- The `select` event was triggering on every navigation change, not just explicit selections
- Board view works correctly because it uses `keys: false` and handles all navigation manually
**Solution:**
1. **Disabled blessed's built-in keyboard handling**: Changed `keys: true` to `keys: false` and `vi: true` to `vi: false`
2. **Removed conflicting select event handler**: The select event was triggering selection callbacks during navigation
3. **Fixed manual navigation**: Updated key handlers to …
> TASK-81 - Fix task list navigation skipping issue

- .backlog/tasks/task-82 - Add-plain-flag-to-task-view-command-for-AI-agents.md
- .cursorrules
- AGENTS.md
- CLAUDE.md
- readme.md
- src/cli.ts
- src/guidelines/.cursorrules.md
- src/guidelines/AGENTS.md
- src/guidelines/CLAUDE.md
- src/test/cli-plain-output.test.ts
- src/test/cli.test.ts
Added `--plain` flag support to both task view commands:
- `backlog task view 81 --plain` - Works correctly
- `backlog task 81 --plain` - Works correctly
The implementation checks for the --plain option and outputs plain text instead of launching the TUI viewer. This makes the output suitable for AI agents to parse.
> TASK-82 - Add --plain flag to task view command for AI agents

- .backlog/tasks/task-82 - Add-plain-flag-to-task-view-command-for-AI-agents.md
- .cursorrules
- AGENTS.md
- CLAUDE.md
- readme.md
- src/cli.ts
- src/guidelines/.cursorrules.md
- src/guidelines/AGENTS.md
- src/guidelines/CLAUDE.md
- src/test/cli-plain-output.test.ts
Added `--plain` flag support to task commands:
- `backlog task view <id> --plain` - Outputs raw markdown content
- `backlog task <id> --plain` - Outputs raw markdown content  
- `backlog task list --plain` - Outputs plain text task list
The implementation simplifies the output to just show the raw markdown file content for task view commands, avoiding duplication of frontmatter data. For the list command, it shows a simple text-based list grouped by status.
- Added workaround for bun compile issue where commander options aren't properly passed through in compiled binaries by checking `process.argv.includes("--plain")`
- Fixed Windows CI test failures by handling Bun.spawnSync stdout/stderr redirection issue
- All commands now output plain text suitable for AI agents to parse without TUI …
> TASK-82 - Add --plain flag to task view command for AI agents (#110)

- .backlog/tasks/readme.md
- .backlog/tasks/task-76 - add-implementation-plan-section.md
- .cursorrules
- AGENTS.md
- CLAUDE.md
- readme.md
- src/cli.ts
- src/guidelines/.cursorrules.md
- src/guidelines/AGENTS.md
- src/guidelines/CLAUDE.md
- src/markdown/serializer.ts
- src/test/implementation-plan.test.ts
*Completed by @claude on 2025-06-19*
- Implemented --plan flag (not -p as originally specified, to avoid conflict with --parent flag)
- Created `updateTaskImplementationPlan` function following the same pattern as `updateTaskAcceptanceCriteria`
- Positioned Implementation Plan section after Acceptance Criteria but before Implementation Notes
- Added comprehensive test suite with 8 tests covering all edge cases
- Used long option --plan instead of short option -p due to Commander.js limitations with two-letter short flags
- Handled empty plan gracefully by not adding the section if plan is empty or whitespace only
- Implemented proper section positioning logic to maintain consistent task file structure
- Updated all guideline files including those in src/guidelines folder
> TASK-76 - Add Implementation Plan section

- .backlog/tasks/task-90 - Fix-task-list-scrolling-behavior-selector-should-move-before-scrolling.md
- src/ui/components/generic-list.ts
- src/ui/task-viewer.ts
The issue was caused by the generic list component using different navigation methods than the board view:
- **Board view**: Uses `keys: false` and `listBox.select(index)` method
- **Generic list**: Was using `keys: true` and `listBox.up()`/`listBox.down()` methods
Modified the generic list component in `/src/ui/components/generic-list.ts`:
1. **Changed navigation methods**: Replaced `listBox.up()` and `listBox.down()` with `listBox.select(current ± 1)`
2. **Updated blessed configuration**: Set `keys: false`, `vi: false`, and `alwaysScroll: false` to match board view
3. **Added arrow key support**: Included `["up", "k"]` and `["down", "j"]` in key bindings
- The cursor now moves through visible items before scrolling begins
- Scrolling behavior matches the board view's intuitive …
> TASK-90 - Fix task list scrolling behavior - selector should move before

- .backlog/tasks/task-94 - cli-show-created-task-file-path.md
- .backlog/tasks/task-96 - Fix-demoted-task-board-visibility-check-status-across-archive-and-drafts.md
- src/cli.ts
- src/core/backlog.ts
- src/file-system/operations.ts
- src/git/operations.ts
- src/test/cli.test.ts
Successfully implemented the file path display feature for CLI task creation. The changes include:
- Modified the `saveTask()` and `saveDraft()` methods in `FileSystem` class to return the absolute file path instead of void
- Updated the `createTask()` and `createDraft()` methods in `Core` class to return the file path from the filesystem operations
- Modified the CLI command handlers to capture and display the returned file path
- Chose to modify the return types of existing methods rather than adding separate methods to get file paths, maintaining a clean API
- Used absolute paths in the output to provide complete file location information
- Maintained backward compatibility by only changing return types (from void to string)
1. `/src/file-system/operations.ts`:
- Changed `saveTask()` …
> TASK-94 - CLI: Show created task file path

- .backlog/tasks/task-97 - Cross-branch-task-ID-checking-and-branch-info.md
- .backlog/tasks/task-98 - Invert-task-order-in-Done-column-only.md
- src/cli.ts
- src/core/backlog.ts
- src/file-system/operations.ts
- src/git/operations.ts
- src/types/index.ts
- src/ui/board.ts
- Added `listAllBranches` and `getFileLastModifiedBranch` to `src/git/operations.ts` to handle git interactions across all branches.
- Modified `generateNextId` in `src/cli.ts` to use `listAllBranches` and `listFilesInTree` to find the max task ID across all local and remote branches.
- Added `branch` property to the `Task` type in `src/types/index.ts`.
- Moved `listTasksWithMetadata` from `src/file-system/operations.ts` to `src/core/backlog.ts` and enhanced it to include the branch name using `getFileLastModifiedBranch`.
- Updated `handleBoardView` in `src/cli.ts` to call the new `core.listTasksWithMetadata` method.
- Modified `renderBoardTui` in `src/ui/board.ts` to display the branch name in the task list on the board.
- Corrected a bug in `src/cli.ts` related to handling of repeatable …
> TASK-97 - Cross-branch task ID checking and branch info

- .backlog/tasks/task-96 - Fix-demoted-task-board-visibility-check-status-across-archive-and-drafts.md
- src/cli.ts
- src/file-system/operations.ts
- Updated `handleBoardView` in `src/cli.ts` to check for demoted or archived tasks across all local and remote branches.
- The new logic fetches all branches, then scans the `.backlog/drafts` and `.backlog/archive/tasks` directories in each branch.
- It collects the IDs of all demoted and archived tasks and uses them to filter the board view, ensuring that these tasks are not displayed.
- This approach avoids modifying the `loadRemoteTasks` function and its associated tests, which were causing issues in the previous implementation.
- All tests are passing with this new implementation.
> TASK-96 - Check status across archive and drafts

- .backlog/tasks/task-98 - Invert-task-order-in-Done-column-only.md
- src/board.ts
- src/ui/board.ts
- Modified `src/ui/board.ts` to change the sort order for the "Done" column to be descending.
- Applied the same logic to `src/board.ts` to ensure that exported boards also reflect the new sort order.
- Kept the ascending sort order for all other columns.
> TASK-98 - Invert task order in Done column only

- .backlog/tasks/task-96 - Fix-demoted-task-board-visibility-check-status-across-archive-and-drafts.md
- src/cli.ts
- src/core/cross-branch-tasks.ts
The initial implementation in commits 71fc0d7 and 6d7b0fd had a critical flaw - it was filtering tasks based on whether they existed in draft/archive folders in ANY branch, rather than checking which state was the most recent. This caused the board to not display any tasks at all.
Created a proper solution that correctly implements cross-branch task state resolution:
1. **New Module**: Created `src/core/cross-branch-tasks.ts` with dedicated functions for:
- `getLatestTaskStates()`: Fetches all branches and checks task files in tasks/drafts/archive directories
- `filterTasksByLatestState()`: Filters tasks to only show those whose latest state is "task"
2. **Key Logic**:
- For each task ID, finds ALL occurrences across ALL branches in all three directories
- Uses `getFileLastModifiedTime()` …
> TASK-96 - Fix demoted task board visibility

- .backlog/tasks/task-99 - Fix-loading-screen-border-rendering-and-improve-UX.md
- src/cli.ts
- src/ui/loading.ts
**Root cause**: Content was overlapping right border due to improper width calculations.
**Key changes**:
- Changed `setImmediate` to `setTimeout(resolve, 10)` for Windows compatibility (lines 205, 275)
- Fixed content positioning: `left: 2, width: "100%-6"` to prevent border overlap (lines 192-194, 261-263)
- Increased box widths to 60-70 chars to prevent text wrapping
- Reduced heights to 5-6 rows for compact display
- Moved spinner to title bar using `loadingBox.setLabel()`
**Files**: `/src/ui/loading.ts`
> TASK-99 - Fix loading screen border rendering and improve UX

- src/cli.ts
- src/markdown/serializer.ts
- src/test/desc-alias.test.ts
- src/test/implementation-notes.test.ts
- src/test/implementation-plan.test.ts
**Approach taken:**
- Added `--desc` as a separate option in Commander.js alongside existing `-d, --description`
- Updated option handling logic in both `buildTaskFromOptions` and task edit command
- Created comprehensive test suite to verify functionality
**Features implemented:**
- `--desc` alias for task create command
- `--desc` alias for task edit command  
- `--desc` alias for draft create command
- Help text shows all available aliases
- Proper handling when both `--description` and `--desc` are provided (uses first one found)
**Technical decisions and trade-offs:**
- **Separate options approach**: Used separate `.option()` calls instead of trying to combine flags, as Commander.js doesn't support multiple long flags in a single option
- **Priority handling**: Used …
> task-106 - Add --desc alias for description flag

- backlog/tasks/task-112 - Add-Tab-key-switching-between-task-and-kanban-views-with-background-loading.md
- src/cli.ts
- src/core/cross-branch-tasks.ts
- src/core/remote-tasks.ts
- src/guidelines/agent-guidelines.md
- src/test/board-command.test.ts
- src/test/cli-agents.test.ts
- src/test/cli-board-integration.test.ts
- src/test/cli-dependency.test.ts
- src/test/cli.test.ts
- src/test/config-commands.test.ts
- src/test/tab-switching.test.ts
- src/test/view-switcher.test.ts
- src/types/index.ts
- src/ui/board.ts
- src/ui/enhanced-views.ts
- src/ui/loading.ts
- src/ui/simple-unified-view.ts
- src/ui/task-viewer.ts
- src/ui/unified-view.ts
- src/ui/view-switcher.ts
**Completed Features:**
1. **View Switcher Architecture** (`src/ui/view-switcher.ts`)
- Created centralized `ViewSwitcher` class for managing view state and transitions
- Implemented `BackgroundLoader` for efficient kanban data preloading with 30-second cache TTL
- Added intelligent background loading that starts when entering task views
- Memory efficient caching to avoid redundant data fetching
2. **Unified View System** (`src/ui/unified-view.ts`)
- Created `runUnifiedView()` function as main entry point for all view operations
- Handles seamless switching between task-list, task-detail, and kanban views
- Integrates with existing loading screens when background data isn't ready
- Preserves state and context when switching between views
3. **Enhanced UI Components**
- **Modified …
> TASK-112 - Add Tab key switching between task and kanban views

- backlog/tasks/task-163 - Fix-intermittent-git-failure-in-task-edit.md
- src/git/operations.ts
- src/test/board-command.test.ts
- src/test/git-isolation.test.ts
- src/ui/view-switcher.ts
Successfully implemented git isolation fix with the following improvements:
**Approach Taken:**
- Identified root cause: addAndCommitTaskFile() was committing ALL staged changes, not just the task file
- Implemented index reset before staging to ensure isolation
- Added retry logic with exponential backoff for transient failures
- Enhanced error handling with detailed staging validation
**Features Implemented:**
- resetIndex() method to clear staging area without affecting working directory
- commitStagedChanges() method with pre-commit validation
- retryGitOperation() method with configurable retry count and exponential backoff
- Isolated git commit logic that only commits the specific task file
**Technical Decisions:**
- Reset index before each task commit to prevent interference from …
> TASK-163 - Fix intermittent git failure in task edit

- README.md
- backlog/config.yml
- backlog/tasks/task-164 - Add-auto_commit-config-option-with-default-false.md
- src/cli.ts
- src/core/backlog.ts
- src/core/config-migration.ts
- src/file-system/operations.ts
- src/test/auto-commit.test.ts
- src/types/index.ts
Successfully implemented autoCommit configuration option with default false value.
**Implementation Details:**
- Added autoCommit field to BacklogConfig type definition
- Updated config migration to include autoCommit with default false for existing projects
- Modified Core class methods to check autoCommit config before performing git operations
- Updated CLI commands to remove hardcoded autoCommit=true parameters
- Added config command support for getting/setting autoCommit option
- All git operations now respect the autoCommit setting from config
**Files Modified:**
- src/types/index.ts - Added autoCommit?: boolean to BacklogConfig
- src/core/config-migration.ts - Added autoCommit: false to defaults and migration
- src/core/backlog.ts - Added shouldAutoCommit() helper and updated all …
> TASK-164 - Add auto_commit config option with default false

- backlog/tasks/task-165 - Fix-BUN_OPTIONS-environment-variable-conflict.md
- src/cli.ts
- src/test/bun-options.test.ts
Successfully implemented intelligent fix for BUN_OPTIONS environment variable conflict.
**Root Cause:**
BUN_OPTIONS environment variable was interfering with CLI execution in the compiled executable, causing 'unknown option' errors like "error: unknown option '--bun'". This occurs because the compiled executable still processes BUN_OPTIONS but Commander.js doesn't understand Bun-specific options.
**Solution Implemented:**
Intelligent solution that temporarily isolates BUN_OPTIONS during CLI parsing while preserving it for subsequent commands:
1. **Temporary Isolation**: Save and clear BUN_OPTIONS before Commander.js processes arguments
2. **Environment Preservation**: Restore BUN_OPTIONS after CLI parsing completes
3. **User-Friendly**: Maintains BUN_OPTIONS for subsequent commands in …
> TASK-165 - Fix BUN_OPTIONS environment variable conflict

- backlog/tasks/task-166 - Audit-and-fix-autoCommit-behavior-across-all-commands.md
- src/agent-instructions.ts
- src/cli.ts
- src/core/backlog.ts
- src/test/auto-commit.test.ts
- src/test/cli.test.ts
- src/test/core.test.ts
- src/test/parent-id-normalization.test.ts
- src/test/remote-id-conflict.test.ts
**Fixed initializeProject method**:
- Changed default from `autoCommit = true` to `autoCommit = false` to match config default
- Method now defaults to not auto-committing, consistent with config interface
**Fixed CLI init command**:
- Simplified to call `initializeProject(name)` without explicit parameter
- Relies on method's default `autoCommit = false` behavior
- Passes explicit `false` to `addAgentInstructions`
**Fixed addAgentInstructions function**:
- Added `autoCommit = false` parameter with default false
- Updated git commit logic to check `autoCommit` parameter
- Updated all call sites to pass autoCommit parameter
**Fixed CLI agents command**:
- Updated to get autoCommit setting from config before calling `addAgentInstructions`
**Files Modified**:
- `src/core/backlog.ts` - Fixed …
> TASK-166 - Audit and fix autoCommit behavior across all commands

- backlog/tasks/task-168 - Fix-editor-integration-issues-with-vim-nano.md
- src/test/editor.test.ts
- src/ui/board.ts
- src/ui/task-viewer.ts
- src/utils/editor.ts
Successfully fixed editor integration issues by switching from synchronous spawnSync to asynchronous spawn. The root cause was that spawnSync with stdio: 'inherit' was interfering with terminal TTY control needed by vim/nano. 
The new implementation uses async spawn with proper event handling for 'close' and 'error' events, allowing terminal editors to function properly without hanging processes or stuck terminals. Updated all UI components (task-viewer.ts, board.ts) to handle async editor calls and updated tests accordingly. 
Also fixed priority order so EDITOR environment variable takes precedence over config defaultEditor, then platform default, which matches standard Unix conventions.
Fixes #163
> TASK-168 - Fix editor integration issues with vim/nano

- backlog/tasks/task-169 - Fix-browser-and-board-crashes.md
- src/server/index.ts
Successfully fixed browser command crash by adding optional chaining to config.autoOpenBrowser access in server/index.ts. 
The root cause was that when config loading fails or no config file exists, loadConfig() returns null, but the code was trying to access config.autoOpenBrowser directly. 
Changed line 25 from 'config.autoOpenBrowser' to 'config?.autoOpenBrowser' to handle null config gracefully. Board command was already working correctly with proper null handling. 
Both commands now handle missing/corrupt config files gracefully with sensible defaults.
Fixes #186
> TASK-169 - Fix browser and board crashes

- README.md
- backlog.md
- backlog/tasks/task-173 - Add-CLI-command-to-export-Kanban-board-to-markdown.md
- src/board.ts
- src/cli.ts
- src/test/board.test.ts
- src/test/cli.test.ts
- Successfully enhanced the existing board export command to meet all acceptance criteria. 
- Modified the CLI command to use Backlog.md as default instead of README.md, added --force flag for overwrite confirmation, and completely rewrote the markdown generation to include proper headers with timestamp and project name. 
- Updated the task format to use **task-ID** - Title with assignees and labels metadata. 
- All tests updated and passing. 
- The export now overwrites files instead of appending for cleaner output.
Closes #140
> TASK-173 - Add CLI command to export Kanban board to markdown

- backlog/tasks/task-184 - Investigate-Windows-bug-with-task-edit-status-command.md
- src/cli.ts
- src/test/cli-parent-filter.test.ts
The issue was caused by a conflict between Commander.js command definitions:
1. Specific command: `.command("edit <taskId>")` with `-s` for setting status
2. Fallback command: `.argument("[taskId]")` that was missing filtering options
When the fallback command didn't support the same options as the list command, it would incorrectly reject valid filtering arguments, causing the "too many arguments" error.
1. **Removed conflicting options** from fallback command to prevent option parsing conflicts
2. **Added command filtering** to prevent fallback from handling reserved command names like "list"
3. **Fixed parent task validation** to be consistent with other error handling (exit code 1)
All command variations now work correctly on Windows:
- `task edit 184 -s "Done" -a "MrLesk" --priority …
> TASK-184 - Fix Windows bug with task edit status command

- backlog/config.yml
- backlog/tasks/task-189 - Fix-CLI-hang-due-to-infinite-loop-in-config-loading.md
- package.json
- src/cli.ts
- src/core/backlog.ts
- src/core/cross-branch-tasks.ts
- src/core/remote-tasks.ts
- src/file-system/operations.ts
- src/test/config-hang-repro.test.ts
- src/test/enhanced-init.test.ts
- src/test/remote-id-conflict.test.ts
- src/types/index.ts
CLI hangs indefinitely on all commands when `backlogDirectory` field is missing from `config.yml`. No error output, process becomes unresponsive and requires force termination. Affects users with legacy configs or manual setup.
Infinite recursion in `src/file-system/operations.ts` during legacy config migration:
```typescript
// loadConfigDirect() line 53-56
if (config && config.backlogDirectory === undefined) {
config.backlogDirectory = ".backlog";
await this.saveConfig(config);  // Triggers circular dependency
}
// saveConfig() line 505  
const backlogDir = await this.getBacklogDir();
// getBacklogDir() line 29-30
if (\!this.cachedConfig) {
this.cachedConfig = await this.loadConfigDirect();  // Back to start
}
```
The legacy config detection calls `saveConfig()` which needs …
> TASK-189 - Fix infinite loop in config loading when backlogDirectory missing

- backlog/tasks/task-192 - Fix-drag-and-drop-not-working-in-web-view.md
- src/web/App.tsx
- src/web/components/Board.tsx
- src/web/components/BoardPage.tsx
- **Root cause**: The drag-and-drop handlers were properly implemented but the UI was not refreshing after successful task updates
- **Fix applied**: Added `onRefreshData` callback prop to Board and BoardPage components to trigger data refresh after drag-and-drop operations
- **Modified files**:
- `src/web/components/Board.tsx`: Added `onRefreshData` prop and called it in `handleTaskUpdate`
- `src/web/components/BoardPage.tsx`: Added `onRefreshData` prop to pass through to Board component
- `src/web/App.tsx`: Passed `refreshData` function to BoardPage component
- **WebSocket observation**: The WebSocket errors mentioned in the bug report were only for health check disconnections, not related to the drag-and-drop functionality
- **Testing**: All existing tests pass, and the fix ensures …
> TASK-192 - Fix drag-and-drop not working in web view

- backlog/tasks/task-194 - Add-graceful-port-handling-for-browser-command.md
- src/server/index.ts
Added comprehensive error handling to the BacklogServer.start() method to catch and gracefully handle port conflicts.
1. **Error Detection**: Wrapped the `Bun.serve()` call in a try-catch block
2. **EADDRINUSE Handling**: Specifically check for EADDRINUSE error code or "address already in use" message
3. **User-Friendly Messages**: Display clear error message with helpful suggestions:
- Try a different port with example command
- Platform-specific commands to find what's using the port (lsof for macOS/Linux, netstat for Windows)
- Advice to kill the conflicting process
4. **Graceful Exit**: Use `process.exit(1)` instead of throwing unhandled exceptions
- `src/server/index.ts`: Added try-catch error handling in the start() method
Tested by:
1. Starting a server on port 6420
2. Attempting …
> TASK-194 - Add graceful port handling for browser command

- backlog/tasks/task-203 - Show-meaningful-description-in-web-kanban.md
- src/web/components/TaskCard.tsx
- Strip raw '## Description' header from task preview in web kanban view
- Display actual task description content for better context
- Implement smart truncation (120 chars) with ellipsis for clean appearance
Fixes #233
> TASK-203 - Show meaningful description in web kanban

- backlog/tasks/task-211 - Add-version-number-display-to-browser-UI.md
- src/server/index.ts
- src/utils/version.ts
- src/web/App.tsx
- src/web/components/SideNavigation.tsx
- src/web/utils/version.ts
Added version display functionality to the browser UI with the following key components:
**Frontend Implementation:**
- Created `src/web/utils/version.ts` utility that fetches version from `/api/version` endpoint
- Modified `src/web/App.tsx` to set version as `data-version` attribute on body tag (`Backlog.md - v{version}`)
- Updated `src/web/components/SideNavigation.tsx` to display version on right side of Settings item when sidebar is expanded
**Backend Implementation:**
- Added `/api/version` endpoint in `src/server/index.ts` with `handleGetVersion()` method
- Leveraged existing `src/utils/version.ts` utility that uses embedded version from compiled binary (same as CLI)
**Key Features:**
- Version displays as "Backlog.md - v{version}" format with small gray text
- Only visible when …
> TASK-211 - Add version number display to browser UI

- .cursorrules
- AGENTS.md
- CLAUDE.md
- GEMINI.md
- backlog/tasks/task-230 - Add-plain-to-task-create-edit-and-print-plain-details-after-operation.md
- src/cli.ts
- src/guidelines/agent-guidelines.md
- src/test/cli-plain-create-edit.test.ts
- Implemented --plain flag for task create/edit. When provided, prints plain formatted task details after operation (starts with File: line). 
- Added tests for both flows asserting File: line, Status/Created/Description/AC sections, and absence of TUI codes. 
- Verified --desc alias works. All tests passing.
> TASK-230 - Add --plain to task create/edit and print plain details after operation

- backlog/tasks/task-217.01 - Sequences-server-endpoints-for-list-and-move.md
- src/core/backlog.ts
- src/core/sequences.ts
- src/server/index.ts
- src/ui/sequences.ts
Implemented sequences endpoints as a thin server bridge to core logic.
Endpoints:
- GET /sequences and GET /api/sequences → core.listActiveSequences() → { unsequenced, sequences } (Done excluded)
- POST /sequences/move and POST /api/sequences/move → core.moveTaskInSequences({ taskId, unsequenced?, targetSequenceIndex? })
-Architecture:
- Server delegates; core owns business rules.
- Core helpers: planMoveToSequence (join semantics + ordinal anchor on Seq 1), planMoveToUnsequenced (isolation check + clear deps/ordinal).
- TUI updated to call the same plan helpers, ensuring consistent behavior across UI and API.
Validation & Persistence:
- Core validates inputs and task existence; server only forwards and returns messages.
- Bulk updates persisted via core.updateTasksBulk; response includes …
> TASK-217.01 - Sequences server: endpoints for list and move

- README.md
- backlog/tasks/task-234 - Investigate-newline-handling-in-CLI-descriptions.md
- src/cli.ts
- src/guidelines/agent-guidelines.md
- src/markdown/serializer.ts
- src/test/description-newlines.test.ts
- Clarifies CLI newline handling: preserves literal newlines; does not interpret `\n` sequences
- Documents multi-line input patterns for Bash/Zsh ($'...'), POSIX (printf), and PowerShell (`n)
- Updates CLI help for create/edit/draft to include concise multi-line examples
- Adds tests to ensure multi‑paragraph descriptions are preserved
- CLI: `--description/--desc` help shows multi-line examples in `src/cli.ts`
- README: Adds "Multi-line descriptions" section with examples
- Tests: `src/test/description-newlines.test.ts`, `src/test/desc-alias.test.ts`, `src/test/cli-plain-create-edit.test.ts`
- `bun run check`
- `bun test src/test/description-newlines.test.ts`
- `bun test src/test/desc-alias.test.ts`
- `bun test src/test/cli-plain-create-edit.test.ts`
Task: task-234
> TASK-234 - Fix CLI newline handling

- AGENTS.md
- CLAUDE.md
- README.md
- backlog/tasks/task-254 - Init-default-'No'-for-Claude-agent-installation.md
- scripts/cli.cjs
- src/cli.ts
- src/markdown/serializer.ts
- src/test/cli-init-claude-default.test.ts
- src/test/cli-priority-filtering.test.ts
- src/test/unicode-rendering.test.ts
Implements TASK-254.
- Interactive init prompt now defaults to No and clarifies: ‘Install Claude Code Backlog.md agent? (y/N) Adds to .claude/agents/’.
- Non-interactive remains opt-in via .
- Added tests covering non-interactive default=false and explicit opt-in.
> TASK-254 - Init: default No for Claude agent install

- README.md
- backlog/tasks/task-250 - Docs-fix-subpath-documents-listing-view-+-unique-IDs.md
- backlog/tasks/task-251 - Board-harden-remote-branch-normalization-to-avoid-origin-origin-refs.md
- backlog/tasks/task-254 - Init-default-'No'-for-Claude-agent-installation.md
- src/cli.ts
- src/file-system/operations.ts
- src/test/docs-recursive.test.ts
Implements TASK-250.
- Filesystem.listDocuments now recursively scans backlog/docs, excluding README.md.
- CLI  and  use recursive search so subpath docs are included and viewable by ID.
-  now sees all local docs (via listDocuments), ensuring global sequential IDs offline.
- Added tests for recursive listing, offline ID generation, and viewing a subdir doc by ID.
Docs updated to clarify IDs are global across subpaths.
Closes #318
> TASK-250 - Docs: recursive listing/view + global IDs

- backlog/tasks/task-258 - Filesystem-ignore-leading-zeros-in-task-IDs.md
- src/test/task-path.test.ts
- src/utils/task-path.ts
Implementation Summary:
- Added numeric, zero-padding-agnostic ID parsing for filesystem resolvers in src/utils/task-path.ts.
- New helpers: parseIdSegments(), extractSegmentsFromFilename(), idsMatchLoosely()
- Updated getTaskPath/getTaskFilename/getDraftPath to fall back to loose numeric matching.
- Added tests validating padded/unpadded and dotted IDs in src/test/task-path.test.ts.
- Verified full test suite passes with zeroPaddedIds=3 and with zeroPaddedIds=0 (via CLI config set).
- No changes to ID generation or file naming; only resolution behavior.
- Lint and type-check pass.
Validation steps performed:
1) bun test (all passing)
2) bun run cli config set zeroPaddedIds 0
3) bun test (all passing)
4) bun run cli config set zeroPaddedIds 3
5) bunx tsc --noEmit && bun run check .
Fixes …
> TASK-258 - Filesystem: ignore leading zeros in task IDs

- backlog/tasks/task-261 - Init-Handle-missing-git-origin-gracefully.md
- src/cli.ts
- src/git/operations.ts
- src/test/no-remote-preflight.test.ts
Implemented git remote preflight for all remote operations.
Summary
- Added GitOperations.hasAnyRemote()/hasRemote() helpers
- Guarded GitOperations.fetch() to skip when no remotes exist with clear warning
- Short-circuited listRemoteBranches/listRecentRemoteBranches when no remotes
- Relied on guarded fetch in doc/decision ID generation and remote loader
- Added tests: no-remote preflight (fetch/log), loadRemoteTasks no-remote, CLI init in no-remote repo
- Ran type-check, lint, and full test suite (all pass)
> TASK-261 - Init: Handle missing git origin gracefully

- AGENTS.md
- README.md
- backlog/tasks/task-256 - Add-CLI-command-to-append-implementation-notes.md
- bun.lock
- src/cli.ts
- src/core/backlog.ts
- src/guidelines/agent-guidelines.md
- src/markdown/serializer.ts
- src/test/acceptance-criteria.test.ts
- src/test/append-implementation-notes.test.ts
- src/test/cli-plain-output.test.ts
- src/test/cli.test.ts
- src/test/core.test.ts
- src/test/implementation-notes-append.test.ts
- src/test/implementation-notes.test.ts
- src/test/implementation-plan.test.ts
- src/test/task-edit-preservation.test.ts
- src/test/test-helpers.ts
- src/test/update-task-description.test.ts
- src/types/index.ts
Implemented append behavior for Implementation Notes via `task edit --append-notes` (append-only).
- Preserves literal newlines; normalizes a single blank line between appended chunks
- Creates section at correct position: after Plan > AC > Description > end
- Supports multiple --append-notes flags per call and repeated invocations
- Prevents mixing replace (`--notes`) with append (`--append-notes`)
Added comprehensive tests for: existing notes append, create-when-missing (with Plan), multi-line content, multiple appends, and flag conflict.
Updated README and Agent Guidelines with examples and newline handling guidance.
Validation: bun test (all green), bunx tsc --noEmit, and bun run check . passed.
> TASK-256 - Add CLI command to append implementation notes

- backlog/tasks/task-273.03 - 273.03-Build-core-Fuse-search-service.md
- src/core/backlog.ts
- src/core/search-service.ts
- src/index.ts
- src/test/search-service.test.ts
- src/types/index.ts
- Added Fuse-backed SearchService wired to the ContentStore and unified SearchResult filtering.
- Extended shared types and Core accessor so CLI/TUI/server can reuse the service.
- Tests: bunx tsc --noEmit; bun run check .; bun test search-service.test.ts.
- Reset initialization state when ContentStore fails so retries are possible.
> TASK-273.03 - Build core Fuse search service

- AGENTS.md
- CLAUDE.md
- GEMINI.md
- backlog/tasks/task-273.05 - 273.05-Server-endpoints-on-shared-store-search.md
- src/core/backlog.ts
- src/core/content-store.ts
- src/core/search-service.ts
- src/server/index.ts
- src/test/server-search-endpoint.test.ts
- src/ui/task-viewer-with-search.ts
- src/web/lib/api.ts
- Centralized server data access via ContentStore/SearchService with loose ID matching helper.
- Added Fuse id/dependency variants plus padded-ID integration tests covering /api/search & /api/task queries.
- Updated TUI list styles to eliminate any-casts; bun run check ., bunx tsc --noEmit, bun test all pass.
> TASK-273.05 - Server endpoints on shared store/search

- backlog/tasks/task-281 - Fix-backlog-init-skip-option.md
- src/cli.ts
- src/test/agent-selection.test.ts
- src/test/cli.test.ts
- src/utils/agent-selection.ts
- Updated `processAgentSelection` to treat a lone "none" selection as an explicit skip and return a skip flag for callers.
- Updated the `backlog init` agent selection flow to honor skip outcomes and log that instructions were skipped instead of forcing a retry.
- Added regression coverage for the skip path in `agent-selection` and CLI integration tests to ensure no agent instruction files are produced when skipping.
- Tests: `bunx tsc --noEmit`, `bun test`, `bun run check .`
> TASK-281 - Fix backlog init skip option

- README.md
- backlog/tasks/task-284 - Simplify-init-flow;-launch-advanced-settings-via-backlog-config.md
- src/cli.ts
- src/commands/advanced-config-wizard.ts
- src/commands/configure-advanced-settings.ts
- src/test/cli.test.ts
- src/test/config-commands.test.ts
- Refactored init advanced prompts into a reusable wizard, reused by `backlog config` and exposed via a new helper.
- Simplified `backlog init` interactive flow to project name → agent instructions → advanced confirmation, applying safe defaults when skipped.
- Updated docs plus added unit coverage for wizard/config flows and CLI summary output.
- Tests: `bunx tsc --noEmit`, `bun run check .`, `bun test`.
> TASK-284 - Simplify init flow; launch advanced settings via backlog config
